package com.example.carrentalapp;

import jakarta.persistence.*;
import java.math.BigDecimal;

/**
 * Represents a car entity in the car rental application.
 * Maps to the 'cars' table in the 'car_rental' schema of the database.
 */
@Entity
@Table(name = "cars", schema = "car_rental")
public class Car {
    /**
     * The unique identifier for the car.
     * It is auto-generated by the database when a new car is added.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idcar")
    private Integer id;

    /**
     * The brand of the car.
     * It is a required field with a maximum length of 50 characters.
     */
    @Column(name = "brand", length = 50, nullable = false)
    private String brand;

    /**
     * The model of the car.
     * It is a required field with a maximum length of 50 characters.
     */
    @Column(name = "model", length = 50, nullable = false)
    private String model;

    /**
     * The engine associated with the car.
     * It is fetched lazily from the database when needed to improve performance.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idengine", nullable = false)
    private Engine engine;

    /**
     * The rental price of the car.
     * It is stored with two decimal places, allowing for prices up to 9999999.99.
     */
    @Column(name = "price", precision = 9, scale = 2, nullable = false)
    private BigDecimal price;

    /**
     * No-arg constructor required by JPA for entity classes.
     */
    public Car() {
        // This constructor is used by JPA to construct entities using reflection.
    }

    /**
     * Constructs a new Car with the specified brand, model, engine, and price.
     *
     * @param brand  The brand of the car.
     * @param model  The model of the car.
     * @param engine The engine associated with the car.
     * @param price  The rental price of the car.
     */
    public Car(String brand, String model, Engine engine, BigDecimal price) {
        this.brand = brand;
        this.model = model;
        this.engine = engine;
        this.price = price;
    }

    // Getters and setters for each field.

    /**
     * Returns the unique identifier of the car.
     *
     * @return The id of the car.
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the car.
     *
     * @param id The new id for the car.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Returns the brand of the car.
     *
     * @return The brand name of the car.
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the brand of the car.
     *
     * @param brand The new brand name for the car.
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * Returns the model of the car.
     *
     * @return The model name of the car.
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets a new model name for this particular car.
     *
     * @param model A String value representing new model name for this particular car.
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * Returns an instance of Engine associated with this particular car.
     *
     * @return An instance of Engine associated with this particular car.
     */
    public Engine getEngine() {
        return engine;
    }

    /**
     * Associates a new instance of Engine with this particular car.
     *
     * @param engine An instance of Engine to be associated with this particular car.
     */
    public void setEngine(Engine engine) {
        this.engine = engine;
    }

    /**
     * Returns rental price for this particular car.
     *
     * @return A BigDecimal value representing rental price for this particular car.
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets a new rental price for this particular car.
     *
     * @param price A BigDecimal value representing new rental price for this particular car.
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    /**
     * Provides a string representation of this Car instance, including id, brand, model, engine, and price.
     *
     * @return A string containing the car's id, brand, model, engine details, and price.
     */
    @Override
    public String toString() {
        return getId() + " " + getBrand() + " " + getModel() + " " + getEngine() + " " + getPrice();
    }
}
